/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "bsp.h"

void main_blinky1(void) {
	while (1) {
		BSP_ledGreenOn();
		BSP_delay(BSP_TICKS_PER_SEC / 4U);
		BSP_ledGreenOff();
		BSP_delay(BSP_TICKS_PER_SEC * 3U / 4U);
	}
}

void main_blinky2(void) {
	while (1) {
		BSP_ledBlueOn();
		BSP_delay(BSP_TICKS_PER_SEC / 2U);
		BSP_ledBlueOff();
		BSP_delay(BSP_TICKS_PER_SEC / 3U);
	}
}

int main(void) {
	uint32_t volatile run = 0U;

	BSP_init();
	if (run) {
		main_blinky1();
	} else {
		main_blinky2();
	}
}
